### ISSUE TITLE
Media and code files on same folder

### ISSUE THREAD

**Issue by nelmiux** [iOS-Mobile-Dev/todo#9]

**Comment by killvung** [comment]
Yea
Connected to "Unnecessary code on some files" issue you bring up, since Xcode had organized everything for us, I am worrying that if we moved the file manually in the folder, it will also confused XCode by unable to read some of the files. 
Even thought, we can try to organize the files manually first, then see what would go wrong.

**Comment by nelmiux** [comment]
You have to update the references. Other thing I noticed you are not complying with apple standard for images. All images you put on the project Apple has standards for them, about sizes and where to put it inside the project. There is an assets place, after you introduce the images on the project.
https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconMatrix.html
